"""
AuditAdapter - UAGF-XAI S6 / Intake Layer
==========================================
Reads an S5 engagement-audit-state JSON and projects it into the
AuditContext data-transfer object consumed by CBEP.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal, List, Optional, get_args

TaskType = Literal[
    "binary_classification",
    "multiclass_classification",
    "regression",
    "forecasting",
    "llm_generation",
    "anomaly_detection",
]


@dataclass
class AuditContext:
    """
    Audit context generated by S5 (UAGF-TAM / AAA).

    The context defines what evidence must be collected according to the
    EU AI Act and the characteristics of the system under audit.
    """

    system_type: str
    modality: str
    application_domain: str
    risk_tier: str
    applicable_articles: List[str]
    blocking_findings: List[str] = field(default_factory=list)
    csp_satisfied: bool = True
    
    model_artifact_uri: Optional[str] = None
    training_dataset_uri: Optional[str] = None
    evaluation_dataset_uri: Optional[str] = None
    sensitive_feature_columns: list[str] = field(default_factory=list)
    target_column: str = "target"
    positive_label: str | int | None = None
    task_type: TaskType = "binary_classification"
    model_format: Optional[str] = None
    model_framework: Optional[str] = None
    provider_name: Optional[str] = None
    output_namespace: Optional[str] = None


_CBEP_ARTICLES: frozenset[str] = frozenset(
    ["Art9", "Art10", "Art13", "Art14", "Art15", "Art61"]
)

_ARTICLE_RE = re.compile(r"^Art\.?(\d+)$")

_ANNEX_III_SECTION_MAP: dict[str, str] = {
    "1": "biometrics",
    "2": "critical_infrastructure",
    "3": "education",
    "4": "employment",
    "5": "essential_services",
    "6": "law_enforcement",
    "7": "migration",
    "8": "justice",
}

def _normalise_article(raw: str) -> str | None:
    m = _ARTICLE_RE.match(raw.strip())
    if m:
        return f"Art{m.group(1)}"
    return None


def _derive_application_domain(data: dict) -> str:
    for mapping in data.get("annex_iii_mapping", []):
        section = str(mapping.get("annex_iii_section", "")).strip()
        if section in _ANNEX_III_SECTION_MAP:
            return _ANNEX_III_SECTION_MAP[section]

        title = str(mapping.get("section_title", "")).lower()
        for domain_label in _ANNEX_III_SECTION_MAP.values():
            if domain_label.replace("_", " ") in title:
                return domain_label

    stage_a = data.get("client_submission", {}).get("stage_a", {})
    ctx = stage_a.get("deployment_context", "")
    return str(ctx).lower() if ctx else "unknown"


def _default_model_metadata(system_type: str) -> tuple[str, str]:
    system_type_normalized = str(system_type).strip().lower()
    if system_type_normalized in {"llm", "agentic"}:
        return "huggingface", "transformers"
    return "joblib", "sklearn"


def _default_task_type(system_type: str) -> TaskType:
    system_type_normalized = str(system_type).strip().lower()
    if system_type_normalized in {"llm", "agentic"}:
        return "llm_generation"
    return "binary_classification"


def _normalize_task_type(raw_value: str, system_type: str) -> TaskType:
    raw = str(raw_value).strip().lower()
    if raw in get_args(TaskType):
        return raw  # type: ignore[return-value]
    return _default_task_type(system_type)


def _default_positive_label(task_type: str):
    if task_type in {"regression", "forecasting", "llm_generation", "anomaly_detection"}:
        return None
    return 1


def _coerce_positive_label(value):
    if value in ("", None):
        return None
    return value


class AuditAdapter:
    """
    Translates S5 JSON outputs into an AuditContext DTO.
    """

    @classmethod
    def from_s5_state(cls, data: dict) -> AuditContext:
        """
        Parse a full S5 engagement-audit-state dict.
        """
        is_llm = bool(data.get("is_llm_or_agentic", False))
        system_type = "llm" if is_llm else "traditional"

        modality = str(
            data.get(
                "verified_modality",
                data.get("modality", data.get("declared_modality", "tabular")),
            )
        )
        risk_tier = str(
            data.get(
                "verified_risk_tier",
                data.get("risk_tier", data.get("declared_risk_tier", "high")),
            )
        )
        application_domain = _derive_application_domain(data)

        compliance_matrix: dict = data.get("compliance_matrix", {})
        raw_articles: list[str] = []
        for raw_key in compliance_matrix:
            token = _normalise_article(raw_key)
            if token and token in _CBEP_ARTICLES:
                raw_articles.append(token)

        applicable_articles = sorted(set(raw_articles), key=lambda a: int(a[3:]))

        blocking_findings: list[str] = list(data.get("blocking_findings", []))
        for item in data.get("cgsa_blocking_findings", []):
            desc = (
                item.get("description", item.get("control_id", str(item)))
                if isinstance(item, dict)
                else str(item)
            )
            if desc and desc not in blocking_findings:
                blocking_findings.append(desc)

        csp_raw = data.get("cgsa_csp_satisfiable")
        if csp_raw is None:
            phase5 = str(data.get("cgsa_phase5_verdict", ""))
            final = str(data.get("final_verdict", ""))
            csp_satisfied = (phase5 == "PASS") or (final == "PASS")
        else:
            csp_satisfied = bool(csp_raw)

        stage_b = data.get("client_submission", {}).get("stage_b", {})
        model_artifact_uri = stage_b.get("model_artifact_uri") or None
        training_dataset_uri = stage_b.get("training_dataset_uri") or None
        evaluation_dataset_uri = stage_b.get("evaluation_dataset_uri") or None
        sensitive_feature_columns = list(
            data.get(
                "sensitive_feature_columns",
                stage_b.get("sensitive_feature_columns", []),
            )
            or []
        )
        target_column = str(
            data.get("target_column", stage_b.get("target_column", "target"))
        )
        task_type = _normalize_task_type(
            data.get("task_type", stage_b.get("task_type", "")),
            system_type,
        )
        positive_label = _coerce_positive_label(
            data.get("positive_label", stage_b.get("positive_label"))
        )
        if positive_label is None:
            positive_label = _default_positive_label(task_type)
        model_format = stage_b.get("model_format") or None
        model_framework = stage_b.get("model_framework") or None
        stage_a = data.get("client_submission", {}).get("stage_a", {})
        provider_name = stage_a.get("provider_name") or data.get("provider_name") or None

        if model_format is None or model_framework is None:
            default_format, default_framework = _default_model_metadata(system_type)
            model_format = model_format or default_format
            model_framework = model_framework or default_framework

        return AuditContext(
            system_type=system_type,
            modality=modality,
            application_domain=application_domain,
            risk_tier=risk_tier,
            applicable_articles=applicable_articles,
            blocking_findings=blocking_findings,
            csp_satisfied=csp_satisfied,
            model_artifact_uri=model_artifact_uri,
            training_dataset_uri=training_dataset_uri,
            evaluation_dataset_uri=evaluation_dataset_uri,
            sensitive_feature_columns=sensitive_feature_columns,
            target_column=target_column,
            positive_label=positive_label,
            task_type=task_type,
            model_format=model_format,
            model_framework=model_framework,
            provider_name=provider_name,
            output_namespace=None,
        )

    @classmethod
    def from_simple_s5(cls, data: dict) -> AuditContext:
        """
        Parse a simplified S5 fixture JSON (legacy compact format).
        """
        system_type_raw = str(data.get("system_type", "traditional ML")).lower()
        system_type = (
            "llm"
            if ("llm" in system_type_raw or "agent" in system_type_raw)
            else "traditional"
        )
        modality = str(data.get("modality", "tabular"))
        risk_tier = str(data.get("risk_level", data.get("risk_tier", "high")))
        domain = str(data.get("domain", "unknown"))

        raw_articles: list[str] = data.get("eu_ai_act_articles", [])
        applicable_articles = sorted(
            {a for a in raw_articles if a in _CBEP_ARTICLES},
            key=lambda a: int(a[3:]),
        )

        model_format = data.get("model_format") or None
        model_framework = data.get("model_framework") or None
        provider_name = data.get("provider_name") or None
        if model_format is None or model_framework is None:
            default_format, default_framework = _default_model_metadata(system_type)
            model_format = model_format or default_format
            model_framework = model_framework or default_framework

        task_type = _normalize_task_type(data.get("task_type", ""), system_type)
        positive_label = _coerce_positive_label(data.get("positive_label"))
        if positive_label is None:
            positive_label = _default_positive_label(task_type)
        sensitive_feature_columns = list(data.get("sensitive_feature_columns", []) or [])

        return AuditContext(
            system_type=system_type,
            modality=modality,
            application_domain=domain,
            risk_tier=risk_tier,
            applicable_articles=applicable_articles,
            blocking_findings=[],
            csp_satisfied=True,
            model_artifact_uri="minio://eng-fdb3a0fd/customer_uploads/model_artifact_uri_7560c5cb_harboursense_v1.4.pkl",
            training_dataset_uri="minio://eng-fdb3a0fd/customer_uploads/training_dataset_uri_0f854c05_training_dataset.csv",
            evaluation_dataset_uri="minio://eng-fdb3a0fd/customer_uploads/evaluation_dataset_uri_ce41b4b8_evaluation_dataset.csv",
            sensitive_feature_columns=sensitive_feature_columns,
            target_column=str(data.get("target_column", "target")),
            positive_label=positive_label,
            task_type=task_type,
            model_format=model_format,
            model_framework=model_framework,
            provider_name=provider_name,
            output_namespace=None,
        )

    @classmethod
    def from_audit_report(cls, data: dict) -> AuditContext:
        """
        Auto-detect input format and dispatch to the correct parser.
        """
        if "verified_modality" in data or "client_submission" in data:
            return cls.from_s5_state(data)
        return cls.from_simple_s5(data)
