"""
AuditAdapter - UAGF-XAI S6 / Intake Layer
==========================================
Reads an S5 engagement-audit-state JSON and projects it into the
AuditContext data-transfer object consumed by CBEP.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal, List, cast, get_args

SystemType = Literal["traditional_ml", "llm", "agentic"]
Modality = Literal[
    "tabular",
    "time_series",
    "text",
    "image",
    "audio",
    "multimodal",
    "unknown",
]

TaskType = Literal[
    "binary_classification",
    "multiclass_classification",
    "regression",
    "forecasting",
    "llm_generation",
    "anomaly_detection",
]

ModelArtifactKind = Literal["single_file", "directory"]


@dataclass
class AuditContext:
    """
    Audit context generated by S5 (UAGF-TAM / AAA).

    The context defines what evidence must be collected according to the
    EU AI Act and the characteristics of the system under audit.
    """

    system_type: SystemType = "traditional_ml"
    modality: Modality = "tabular"
    application_domain: str | None = None
    risk_tier: str | None = None
    applicable_articles: List[str] = field(default_factory=list)
    blocking_findings: list = field(default_factory=list)
    csp_satisfied: bool = True

    task_type: TaskType | None = None
    provider_name: str | None = None

    model_artifact_uri: str | None = None
    model_artifact_kind: ModelArtifactKind | None = None
    model_format: str | None = None
    model_framework: str | None = None
    model_type: str | None = None
    model_entrypoint: str | None = None

    # traditional ML resources
    training_dataset_uri: str | None = None
    evaluation_dataset_uri: str | None = None
    target_column: str | None = None
    positive_label: str | int | None = None
    feature_columns: list[str] | None = None
    sensitive_feature_columns: list[str] = field(default_factory=list)
    actionable_feature_columns: list[str] | None = None
    immutable_feature_columns: list[str] = field(default_factory=list)

    # LLM / Agentic resources
    golden_set_uri: str | None = None
    system_prompt_uri: str | None = None
    rag_manifest_uri: str | None = None
    guardrail_config_uri: str | None = None

    def __post_init__(self):
        """Normalize direct DTO construction to the public S5/S6 vocabulary."""
        normalized = _normalize_text(self.system_type).replace(" ", "_")
        self.system_type = (
            normalized if normalized in {"llm", "agentic"} else "traditional_ml"
        )
        self.modality = _normalize_modality_value(self.modality)


_CBEP_ARTICLES = frozenset(["Art9", "Art10", "Art13", "Art14", "Art15", "Art61"])

_ARTICLE_RE = re.compile(r"^Art\.?(\d+)$")

# EU AI Act Annex III lists high-risk AI system use-case areas.
# This mapping converts Annex III section numbers from S5 audit input
# into normalized UAGF-XAI application_domain labels.
# Source: Regulation (EU) 2024/1689, Annex III.
_ANNEX_III_SECTION_MAP: dict[str, str] = {
    "1": "biometrics",
    "2": "critical_infrastructure",
    "3": "education",
    "4": "employment",
    "5": "essential_services",
    "6": "law_enforcement",
    "7": "migration",
    "8": "justice",
}


def _normalize_text(value) -> str:
    return str(value).strip().lower() if value is not None else ""


def _normalize_modality_value(value) -> Modality:
    normalized = _normalize_text(value).replace("-", "_").replace(" ", "_")
    aliases = {
        "agentic": "text",
        "llm": "text",
        "nlp": "text",
        "language": "text",
        "natural_language": "text",
        "timeseries": "time_series",
    }
    normalized = aliases.get(normalized, normalized)
    allowed = set(get_args(Modality))
    if normalized not in allowed:
        return "unknown"
    return normalized  # type: ignore[return-value]


def _coerce_bool(value) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"true", "1", "yes"}:
            return True
        if normalized in {"false", "0", "no", ""}:
            return False
    return bool(value)


def _coerce_optional_text(value) -> str | None:
    if value in ("", None):
        return None
    return str(value)


def _coerce_optional_string_list(value, field_name: str) -> list[str] | None:
    if value is None:
        return None
    if not isinstance(value, list):
        raise ValueError(f"{field_name} must be a list of non-empty strings.")

    result = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{field_name} must contain only non-empty strings.")
        normalized = item.strip()
        if normalized not in result:
            result.append(normalized)
    return result


def _coerce_policy_columns(value, field_name: str, default):
    if value is None:
        return default
    if not isinstance(value, list):
        raise ValueError(f"{field_name} must be a list of non-empty strings.")
    result = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{field_name} must contain only non-empty strings.")
        normalized = item.strip()
        if normalized in result:
            raise ValueError(f"{field_name} must not contain duplicate columns.")
        result.append(normalized)
    return result


def _derive_application_domain(data: dict) -> str:
    for mapping in data.get("annex_iii_mapping", []):
        section = str(mapping.get("annex_iii_section", "")).strip()
        if section in _ANNEX_III_SECTION_MAP:
            return _ANNEX_III_SECTION_MAP[section]

        title = str(mapping.get("section_title", "")).lower()
        for domain_label in _ANNEX_III_SECTION_MAP.values():
            if domain_label.replace("_", " ") in title:
                return domain_label

    stage_a = data.get("client_submission", {}).get("stage_a", {})
    ctx = stage_a.get("deployment_context", "")
    return str(ctx).lower() if ctx else "unknown"


def _derive_system_type(data: dict, stage_a: dict, stage_b: dict) -> SystemType:
    """Derive the canonical system family with the S5 LLM flag as authority."""
    is_llm_or_agentic = _coerce_bool(
        data.get("is_llm_or_agentic")
        or stage_b.get("is_llm_or_agentic")
    )
    if not is_llm_or_agentic:
        return "traditional_ml"

    text_pool = " ".join(
        _normalize_text(value)
        for value in (
            data.get("system_type"),
            data.get("modality"),
            data.get("declared_modality"),
            data.get("verified_modality"),
            stage_a.get("declared_modality"),
            stage_b.get("system_type"),
            stage_b.get("modality"),
            stage_b.get("declared_modality"),
            stage_b.get("verified_modality"),
            stage_b.get("model_type"),
            stage_b.get("general_description"),
        )
    )
    if any(
        token in text_pool
        for token in ("agentic", "tool-calling", "tool calling", "tool_calling")
    ):
        return "agentic"
    return "llm"


def _derive_modality(data: dict, stage_a: dict, stage_b: dict) -> Modality:
    raw_modality = (
        data.get("verified_modality")
        or data.get("modality")
        or data.get("declared_modality")
        or stage_a.get("declared_modality")
        or stage_b.get("verified_modality")
        or stage_b.get("modality")
        or stage_b.get("declared_modality")
    )
    return _normalize_modality_value(raw_modality)


def _build_context(data: dict, stage_b: dict, stage_a: dict) -> AuditContext:
    system_type = _derive_system_type(data, stage_a, stage_b)
    modality = _derive_modality(data, stage_a, stage_b)
    risk_tier = _coerce_optional_text(
        data.get("verified_risk_tier")
        or data.get("risk_tier")
        or data.get("declared_risk_tier")
    )
    application_domain = _derive_application_domain(data)

    compliance_matrix: dict = data.get("compliance_matrix", {})
    raw_articles: list[str] = []
    for raw_key in compliance_matrix:
        match = _ARTICLE_RE.match(raw_key.strip())
        token = f"Art{match.group(1)}" if match else None
        if token and token in _CBEP_ARTICLES:
            raw_articles.append(token)

    applicable_articles = sorted(set(raw_articles), key=lambda a: int(a[3:]))

    blocking_findings: list[str] = list(data.get("blocking_findings", []))
    for item in data.get("cgsa_blocking_findings", []):
        desc = (
            item.get("description", item.get("control_id", str(item)))
            if isinstance(item, dict)
            else str(item)
        )
        if desc and desc not in blocking_findings:
            blocking_findings.append(desc)

    csp_raw = data.get("cgsa_csp_satisfiable")
    if csp_raw is None:
        phase5 = str(data.get("cgsa_phase5_verdict", ""))
        final = str(data.get("final_verdict", ""))
        csp_satisfied = (phase5 == "PASS") or (final == "PASS")
    else:
        csp_satisfied = bool(csp_raw)

    model_artifact_uri = _coerce_optional_text(stage_b.get("model_artifact_uri"))
    raw_artifact_kind = _normalize_text(stage_b.get("model_artifact_kind"))
    if raw_artifact_kind and raw_artifact_kind not in {"single_file", "directory"}:
        raise ValueError(
            "client_submission.stage_b.model_artifact_kind must be "
            "'single_file' or 'directory'."
        )
    model_artifact_kind = (
        cast(ModelArtifactKind, raw_artifact_kind) if raw_artifact_kind else None
    )
    model_format = _coerce_optional_text(stage_b.get("model_format"))
    model_framework = _coerce_optional_text(stage_b.get("model_framework"))
    model_type = _coerce_optional_text(stage_b.get("model_type"))
    model_entrypoint = _coerce_optional_text(stage_b.get("model_entrypoint"))
    training_dataset_uri = _coerce_optional_text(stage_b.get("training_dataset_uri"))
    evaluation_dataset_uri = _coerce_optional_text(stage_b.get("evaluation_dataset_uri"))
    target_column = _coerce_optional_text(stage_b.get("target_column"))
    positive_label = stage_b.get("positive_label")
    positive_label = None if positive_label in ("", None) else positive_label

    data_dictionary = stage_b.get("data_dictionary") or {}
    if "feature_columns" in data:
        raw_feature_columns = data["feature_columns"]
    elif "feature_columns" in stage_b:
        raw_feature_columns = stage_b["feature_columns"]
    else:
        raw_feature_columns = data_dictionary.get("feature_columns")
    feature_columns = _coerce_optional_string_list(
        raw_feature_columns,
        "feature_columns",
    )
    if target_column and feature_columns and target_column in feature_columns:
        raise ValueError("feature_columns must not include target_column.")

    sensitive_feature_columns = stage_b.get("sensitive_feature_columns") or []
    if not isinstance(sensitive_feature_columns, list):
        sensitive_feature_columns = [sensitive_feature_columns]
    sensitive_feature_columns = [
        str(item) for item in sensitive_feature_columns if item not in ("", None)
    ]
    actionable_columns = _coerce_policy_columns(
        stage_b.get("actionable_feature_columns"),
        "actionable_feature_columns",
        None,
    )
    immutable_columns = _coerce_policy_columns(
        stage_b.get("immutable_feature_columns"),
        "immutable_feature_columns",
        [],
    )

    golden_set_uri = _coerce_optional_text(stage_b.get("golden_set_uri"))
    system_prompt_uri = _coerce_optional_text(stage_b.get("system_prompt_uri"))
    rag_manifest_uri = _coerce_optional_text(stage_b.get("rag_manifest_uri"))
    guardrail_config_uri = _coerce_optional_text(stage_b.get("guardrail_config_uri"))
    task_type_raw = stage_b.get("task_type")
    normalized_task_type = _normalize_text(task_type_raw)
    if normalized_task_type and normalized_task_type not in get_args(TaskType):
        raise ValueError(
            "client_submission.stage_b.task_type has an unsupported value: "
            f"{task_type_raw!r}."
        )
    task_type = cast(TaskType, normalized_task_type) if normalized_task_type else None

    provider_name = (
        stage_a.get("provider_name")
        or data.get("provider_name")
        or stage_b.get("provider_name")
        or None
    )

    return AuditContext(
        system_type=system_type,
        modality=modality,
        application_domain=application_domain,
        risk_tier=risk_tier,
        applicable_articles=applicable_articles,
        blocking_findings=blocking_findings,
        csp_satisfied=csp_satisfied,
        model_artifact_uri=model_artifact_uri,
        model_artifact_kind=model_artifact_kind,
        model_format=model_format,
        model_framework=model_framework,
        model_type=model_type,
        model_entrypoint=model_entrypoint,
        training_dataset_uri=training_dataset_uri,
        evaluation_dataset_uri=evaluation_dataset_uri,
        target_column=target_column,
        positive_label=positive_label,
        feature_columns=feature_columns,
        sensitive_feature_columns=sensitive_feature_columns,
        actionable_feature_columns=actionable_columns,
        immutable_feature_columns=immutable_columns,
        golden_set_uri=golden_set_uri,
        system_prompt_uri=system_prompt_uri,
        rag_manifest_uri=rag_manifest_uri,
        guardrail_config_uri=guardrail_config_uri,
        task_type=task_type,
        provider_name=provider_name,
    )


class AuditAdapter:
    """
    Translates S5 JSON outputs into an AuditContext DTO.
    """

    @classmethod
    def from_s5_state(cls, data: dict) -> AuditContext:
        """
        Parse a full S5 engagement-audit-state dict.
        """
        client_submission = data.get("client_submission", {})
        stage_a = client_submission.get("stage_a", {})
        stage_b = client_submission.get("stage_b", {})
        return _build_context(data, stage_b, stage_a)

    @classmethod
    def from_simple_s5(cls, data: dict) -> AuditContext:
        """
        Parse a simplified S5 fixture JSON (legacy compact format).
        """
        stage_a = data.get("stage_a", {})
        return _build_context(data, data, stage_a)

    @classmethod
    def from_audit_report(cls, data: dict) -> AuditContext:
        """
        Auto-detect input format and dispatch to the correct parser.
        """
        if "verified_modality" in data or "client_submission" in data:
            return cls.from_s5_state(data)
        return cls.from_simple_s5(data)
