"""
AuditAdapter - UAGF-XAI S6 / Intake Layer
==========================================
Reads an S5 engagement-audit-state JSON and projects it into the
AuditContext data-transfer object consumed by CBEP.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal, List, Optional, get_args

TaskType = Literal[
    "binary_classification",
    "multiclass_classification",
    "regression",
    "forecasting",
    "llm_generation",
    "anomaly_detection",
]


@dataclass
class AuditContext:
    """
    Audit context generated by S5 (UAGF-TAM / AAA).

    The context defines what evidence must be collected according to the
    EU AI Act and the characteristics of the system under audit.
    """

    system_type: str | None = None
    modality: str | None = None
    application_domain: str | None = None
    risk_tier: str | None = None
    applicable_articles: List[str] = field(default_factory=list)
    blocking_findings: list = field(default_factory=list)
    csp_satisfied: bool = True

    model_artifact_uri: str | None = None
    model_format: str | None = None
    model_framework: str | None = None
    model_type: str | None = None
    model_entrypoint: str | None = None

    training_dataset_uri: str | None = None
    evaluation_dataset_uri: str | None = None
    target_column: str | None = None
    positive_label: str | int | None = None
    sensitive_feature_columns: list[str] = field(default_factory=list)

    golden_set_uri: str | None = None
    system_prompt_uri: str | None = None
    rag_manifest_uri: str | None = None
    guardrail_config_uri: str | None = None

    task_type: TaskType | None = None
    provider_name: str | None = None
    output_namespace: str | None = None


_CBEP_ARTICLES: frozenset[str] = frozenset(
    ["Art9", "Art10", "Art13", "Art14", "Art15", "Art61"]
)

_ARTICLE_RE = re.compile(r"^Art\.?(\d+)$")

_ANNEX_III_SECTION_MAP: dict[str, str] = {
    "1": "biometrics",
    "2": "critical_infrastructure",
    "3": "education",
    "4": "employment",
    "5": "essential_services",
    "6": "law_enforcement",
    "7": "migration",
    "8": "justice",
}


def _normalise_article(raw: str) -> str | None:
    m = _ARTICLE_RE.match(raw.strip())
    if m:
        return f"Art{m.group(1)}"
    return None


def _normalize_text(value) -> str:
    return str(value).strip().lower() if value is not None else ""


def _coerce_optional_text(value) -> str | None:
    if value in ("", None):
        return None
    return str(value)


def _as_string_list(value) -> list[str]:
    if not value:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if item not in ("", None)]
    return [str(value)]


def _derive_application_domain(data: dict) -> str:
    for mapping in data.get("annex_iii_mapping", []):
        section = str(mapping.get("annex_iii_section", "")).strip()
        if section in _ANNEX_III_SECTION_MAP:
            return _ANNEX_III_SECTION_MAP[section]

        title = str(mapping.get("section_title", "")).lower()
        for domain_label in _ANNEX_III_SECTION_MAP.values():
            if domain_label.replace("_", " ") in title:
                return domain_label

    stage_a = data.get("client_submission", {}).get("stage_a", {})
    ctx = stage_a.get("deployment_context", "")
    return str(ctx).lower() if ctx else "unknown"


def _default_model_metadata(system_type: str) -> tuple[str, str]:
    system_type_normalized = _normalize_text(system_type)
    if system_type_normalized in {"llm", "agentic"}:
        return "huggingface", "transformers"
    return "joblib", "sklearn"


def _default_task_type(system_type: str) -> TaskType:
    system_type_normalized = _normalize_text(system_type)
    if system_type_normalized in {"llm", "agentic"}:
        return "llm_generation"
    return "binary_classification"


def _normalize_task_type(raw_value, system_type: str) -> TaskType:
    raw = _normalize_text(raw_value)
    if raw in get_args(TaskType):
        return raw  # type: ignore[return-value]
    return _default_task_type(system_type)


def _default_positive_label(task_type: str):
    if task_type in {
        "regression",
        "forecasting",
        "llm_generation",
        "anomaly_detection",
    }:
        return None
    return 1


def _coerce_positive_label(value):
    if value in ("", None):
        return None
    return value


def _looks_like_llm_model(model_type: str | None) -> bool:
    model_type_norm = _normalize_text(model_type)
    if not model_type_norm:
        return False
    return any(
        token in model_type_norm
        for token in ("llm", "rag", "agentic", "mistral", "lora")
    )


def _infer_system_type(
    explicit_system_type,
    is_llm_or_agentic,
    model_type: str | None,
) -> str:
    explicit = _normalize_text(explicit_system_type)
    model_type_norm = _normalize_text(model_type)
    llm_like = bool(is_llm_or_agentic) or _looks_like_llm_model(model_type)

    if explicit in {"llm", "agentic"} or llm_like:
        if explicit == "agentic" or "agentic" in model_type_norm:
            return "agentic"
        return "llm"

    return explicit or "traditional"


def _build_context(data: dict, stage_b: dict, stage_a: dict) -> AuditContext:
    is_llm_or_agentic = data.get("is_llm_or_agentic") or stage_b.get(
        "is_llm_or_agentic"
    )

    model_type = _coerce_optional_text(
        data.get("model_type") or stage_b.get("model_type")
    )
    system_type = _infer_system_type(
        data.get("system_type")
        or data.get("declared_modality")
        or data.get("verified_modality")
        or data.get("modality"),
        is_llm_or_agentic,
        model_type,
    )

    modality = _coerce_optional_text(
        data.get("verified_modality")
        or data.get("modality")
        or data.get("declared_modality")
    )
    risk_tier = _coerce_optional_text(
        data.get("verified_risk_tier")
        or data.get("risk_tier")
        or data.get("declared_risk_tier")
    )
    application_domain = _derive_application_domain(data)

    compliance_matrix: dict = data.get("compliance_matrix", {})
    raw_articles: list[str] = []
    for raw_key in compliance_matrix:
        token = _normalise_article(raw_key)
        if token and token in _CBEP_ARTICLES:
            raw_articles.append(token)

    applicable_articles = sorted(set(raw_articles), key=lambda a: int(a[3:]))

    blocking_findings: list[str] = list(data.get("blocking_findings", []))
    for item in data.get("cgsa_blocking_findings", []):
        desc = (
            item.get("description", item.get("control_id", str(item)))
            if isinstance(item, dict)
            else str(item)
        )
        if desc and desc not in blocking_findings:
            blocking_findings.append(desc)

    csp_raw = data.get("cgsa_csp_satisfiable")
    if csp_raw is None:
        phase5 = str(data.get("cgsa_phase5_verdict", ""))
        final = str(data.get("final_verdict", ""))
        csp_satisfied = (phase5 == "PASS") or (final == "PASS")
    else:
        csp_satisfied = bool(csp_raw)

    model_artifact_uri = _coerce_optional_text(
        data.get("model_artifact_uri") or stage_b.get("model_artifact_uri")
    )
    model_format = _coerce_optional_text(
        data.get("model_format") or stage_b.get("model_format")
    )
    model_framework = _coerce_optional_text(
        data.get("model_framework") or stage_b.get("model_framework")
    )
    model_entrypoint = _coerce_optional_text(
        data.get("model_entrypoint") or stage_b.get("model_entrypoint")
    )

    training_dataset_uri = _coerce_optional_text(
        data.get("training_dataset_uri") or stage_b.get("training_dataset_uri")
    )
    evaluation_dataset_uri = _coerce_optional_text(
        data.get("evaluation_dataset_uri") or stage_b.get("evaluation_dataset_uri")
    )

    target_column = _coerce_optional_text(
        data.get("target_column") or stage_b.get("target_column")
    )

    positive_label = _coerce_positive_label(
        data.get("positive_label")
        if "positive_label" in data
        else stage_b.get("positive_label")
    )

    sensitive_feature_columns = _as_string_list(
        data.get("sensitive_feature_columns")
        or stage_b.get("sensitive_feature_columns")
        or []
    )

    golden_set_uri = _coerce_optional_text(
        data.get("golden_set_uri") or stage_b.get("golden_set_uri")
    )
    system_prompt_uri = _coerce_optional_text(
        data.get("system_prompt_uri") or stage_b.get("system_prompt_uri")
    )
    rag_manifest_uri = _coerce_optional_text(
        data.get("rag_manifest_uri") or stage_b.get("rag_manifest_uri")
    )
    guardrail_config_uri = _coerce_optional_text(
        data.get("guardrail_config_uri") or stage_b.get("guardrail_config_uri")
    )

    task_type_raw = data.get("task_type") or stage_b.get("task_type")
    if task_type_raw is None and (
        is_llm_or_agentic or system_type in {"llm", "agentic"}
    ):
        task_type_raw = "llm_generation"

    task_type = _normalize_task_type(task_type_raw, system_type)
    if _looks_like_llm_model(model_type):
        task_type = "llm_generation"
        if system_type not in {"llm", "agentic"}:
            system_type = "agentic"

    if positive_label is None:
        positive_label = _default_positive_label(task_type)

    if model_format is None or model_framework is None:
        default_format, default_framework = _default_model_metadata(system_type)
        model_format = model_format or default_format
        model_framework = model_framework or default_framework

    if target_column is None and task_type != "llm_generation":
        target_column = "target"

    stage_a_provider = stage_a.get("provider_name")
    provider_name = (
        stage_a_provider
        or data.get("provider_name")
        or stage_b.get("provider_name")
        or None
    )

    return AuditContext(
        system_type=system_type,
        modality=modality,
        application_domain=application_domain,
        risk_tier=risk_tier,
        applicable_articles=applicable_articles,
        blocking_findings=blocking_findings,
        csp_satisfied=csp_satisfied,
        model_artifact_uri=model_artifact_uri,
        model_format=model_format,
        model_framework=model_framework,
        model_type=model_type,
        model_entrypoint=model_entrypoint,
        training_dataset_uri=training_dataset_uri,
        evaluation_dataset_uri=evaluation_dataset_uri,
        target_column=target_column,
        positive_label=positive_label,
        sensitive_feature_columns=sensitive_feature_columns,
        golden_set_uri=golden_set_uri,
        system_prompt_uri=system_prompt_uri,
        rag_manifest_uri=rag_manifest_uri,
        guardrail_config_uri=guardrail_config_uri,
        task_type=task_type,
        provider_name=provider_name,
        output_namespace=None,
    )


class AuditAdapter:
    """
    Translates S5 JSON outputs into an AuditContext DTO.
    """

    @classmethod
    def from_s5_state(cls, data: dict) -> AuditContext:
        """
        Parse a full S5 engagement-audit-state dict.
        """
        client_submission = data.get("client_submission", {})
        stage_a = client_submission.get("stage_a", {})
        stage_b = client_submission.get("stage_b", {})
        return _build_context(data, stage_b, stage_a)

    @classmethod
    def from_simple_s5(cls, data: dict) -> AuditContext:
        """
        Parse a simplified S5 fixture JSON (legacy compact format).
        """
        stage_a = data.get("stage_a", {})
        return _build_context(data, data, stage_a)

    @classmethod
    def from_audit_report(cls, data: dict) -> AuditContext:
        """
        Auto-detect input format and dispatch to the correct parser.
        """
        if "verified_modality" in data or "client_submission" in data:
            return cls.from_s5_state(data)
        return cls.from_simple_s5(data)
